import { formatMoney } from '../../../shared/money/format-money';
import type { SaleStatus } from '../api/sales.api';

export const SALES_LABELS = {
  nav: 'Satışlar',
  title: 'Satışlar',
  description: 'Məhsul satışlarını yaradın, təsdiqləyin və izləyin.',
  create: 'Yeni satış',
  edit: 'Satışı redaktə et',
  detail: 'Satış məlumatları',
  printTitle: 'Satış sənədi',
  statuses: {
    DRAFT: 'Qaralama',
    POSTED: 'Təsdiqlənib',
    CANCELLED: 'Ləğv edilib',
  } satisfies Record<SaleStatus, string>,
  columns: {
    documentNumber: 'Sənəd nömrəsi',
    businessDate: 'Əməliyyat tarixi',
    partner: 'Müştəri',
    status: 'Status',
    itemCount: 'Sətir sayı',
    subtotal: 'Ara cəm',
    discount: 'Endirim',
    total: 'Yekun məbləğ',
    createdBy: 'Yaradan',
    createdAt: 'Yaradılma vaxtı',
    actions: 'Əməliyyatlar',
  },
  filters: {
    documentNumber: 'Sənəd nömrəsi',
    documentNumberPlaceholder: 'Sənəd nömrəsini axtarın',
    partner: 'Müştəri',
    status: 'Status',
    dateRange: 'Əməliyyat tarixi',
    dateFrom: 'Başlanğıc tarixi',
    dateTo: 'Bitmə tarixi',
    product: 'Məhsul',
    minTotal: 'Minimum məbləğ',
    maxTotal: 'Maksimum məbləğ',
    all: 'Hamısı',
  },
  fields: {
    partner: 'Müştəri',
    partnerPlaceholder: 'Müştəri seçin',
    businessDate: 'Əməliyyat tarixi',
    notes: 'Qeyd',
    notesPlaceholder: 'Satış barədə qeyd daxil edin',
    documentDiscount: 'Sənəd endirimi',
    product: 'Məhsul',
    productPlaceholder: 'Məhsul seçin',
    availableQuantity: 'Cari miqdar',
    quantity: 'Miqdar',
    unitPrice: 'Vahid qiyməti',
    lineDiscount: 'Sətir endirimi',
    lineTotal: 'Sətir yekunu',
    lineNotes: 'Sətir qeydi',
    lineNotesPlaceholder: 'Sətir barədə qeyd',
    items: 'Məhsul sətirləri',
    costAtPosting: 'Təsdiq anı maya dəyəri',
    partnerDebt: 'Cari borc qalığı',
    itemCount: 'Sətir sayı',
    totalQuantity: 'Ümumi miqdar',
    projectedDebt: 'Təsdiqdən sonra borc',
  },
  actions: {
    view: 'Bax',
    edit: 'Redaktə et',
    post: 'Təsdiqlə',
    remove: 'Sil',
    cancel: 'Ləğv et',
    save: 'Yadda saxla',
    saveAndPost: 'Təsdiqlə',
    back: 'Geri',
    addLine: 'Sətir əlavə et',
    removeLine: 'Sətiri sil',
    retry: 'Yenidən cəhd et',
    confirm: 'Təsdiqlə',
    print: 'Çap et',
  },
  post: {
    title: 'Satışı təsdiqləyirsiniz?',
    text: 'Təsdiqdən sonra məhsul miqdarı azalacaq, satış redaktə üçün bağlanacaq. «Ödəniş qəbul et» seçildikdə ayrıca Mədaxil kassa əməliyyatı yaradılır.',
    negativeQuantityAlert:
      'Bəzi məhsulların miqdarı mənfiyə düşəcək. Davam etmək üçün səbəb daxil edin.',
    negativeQuantityReason: 'Mənfi miqdar səbəbi',
    negativeQuantityReasonPlaceholder: 'Mənfi miqdar səbəbini daxil edin',
    negativeQuantityReasonRequired: 'Mənfi miqdar səbəbi mütləqdir.',
    acceptPayment: 'Ödəniş qəbul et',
    acceptPaymentHint:
      'Yalnız «Təsdiqlə» zamanı ayrıca Mədaxil kassa əməliyyatı yaradılır.',
    cashAccount: 'Kassa hesabı',
    cashAccountPlaceholder: 'Kassa hesabı seçin',
    paymentAmount: 'Ödəniş məbləği',
    paymentAmountPlaceholder: '0.00',
    paymentAmountHint:
      'Qismən və ya sənəd məbləğindən artıq ödənişə icazə verilir.',
    immediatePaymentRequired: 'Ödəniş üçün kassa hesabı və məbləğ mütləqdir.',
    previewTitle: 'Təsdiqdən sonra təxmini qalıqlar',
    partnerDebtBefore: 'Tərəfdaş borcu (əvvəl)',
    partnerDebtAfter: 'Tərəfdaş borcu (sonra)',
    cashBefore: 'Kassa qalığı (əvvəl)',
    cashAfter: 'Kassa qalığı (sonra)',
    success: 'Satış təsdiqləndi.',
  },
  cancel: {
    title: 'Satışı ləğv edirsiniz?',
    text: 'Bu tamamlanmış satışı ləğv etmək geri qaytarıla bilməz. Aşağıdakı təsirlər eyni vaxtda tətbiq olunacaq.',
    effectsTitle: 'Ləğv nəticələri',
    effects: [
      'Məhsul miqdarı orijinal satış qədər bərpa olunacaq (tarixçə saxlanılır).',
      'Tərəfdaş borcu orijinal satış məbləği qədər azalacaq (borc hərəkəti saxlanılır).',
      'Kassa balansı bu ləğvdən dəyişmir — əlaqəli tamamlanmış mədaxili əvvəlcə ayrıca ləğv edin.',
      'Sənəd «Ləğv edilib» statusunda qalır; yenidən təsdiq edilə bilməz.',
    ],
    reason: 'Ləğv səbəbi',
    reasonPlaceholder: 'Ləğv səbəbini daxil edin',
    reasonRequired: 'Ləğv səbəbi mütləqdir.',
    success: 'Satış ləğv edildi.',
  },
  remove: {
    title: 'Qaralama satış silinsin?',
    text: 'Bu əməliyyatı geri qaytarmaq mümkün deyil.',
    success: 'Qaralama satış silindi.',
  },
  messages: {
    empty: 'Satış tapılmadı.',
    loading: 'Məlumatlar yüklənir...',
    loadError: 'Satış məlumatlarını yükləmək mümkün olmadı.',
    printOpenError: 'Çap pəncərəsini açmaq mümkün olmadı.',
    createSuccess: 'Qaralama satış yaradıldı.',
    updateSuccess: 'Qaralama satış yeniləndi.',
    draftOnly: 'Yalnız qaralama satış redaktə edilə bilər.',
  },
  audit: {
    title: 'Audit məlumatları',
    createdBy: 'Yaradan',
    postedBy: 'Təsdiqləyən',
    cancelledBy: 'Ləğv edən',
    postedAt: 'Təsdiq vaxtı',
    cancelledAt: 'Ləğv vaxtı',
    cancelReason: 'Ləğv səbəbi',
    negativeQuantityOverrideReason: 'Mənfi miqdar səbəbi',
  },
  history: {
    quantity: 'Miqdar tarixçəsi',
    debt: 'Borc hərəkətləri',
    cash: 'Əlaqəli kassa əməliyyatları',
    cashCancelledHint:
      'Ləğv edilmiş kassa əməliyyatları aktiv ödəniş sayılmır; tarixçə üçün saxlanılır.',
    change: 'Dəyişiklik',
    before: 'Əvvəl',
    after: 'Sonra',
    reason: 'Səbəb',
    date: 'Tarix',
    signedAmount: 'Məbləğ təsiri',
    transactionNumber: 'Əməliyyat №',
    cashAccount: 'Kassa hesabı',
    amount: 'Məbləğ',
  },
  formatMoney,
} as const;

export function saleStatusLabel(status: SaleStatus): string {
  return SALES_LABELS.statuses[status];
}
