/**
 * Azerbaijani UI labels for Cash (ADR-005). Never expose enum keys.
 */
export const CASH_LABELS = {
  nav: "Kassa",
  navAccounts: "Kassa hesabları",
  navReports: "Hesabatlar",
  navTransactions: "Əməliyyatlar",
  allTransactionsTitle: "Bütün kassa əməliyyatları",
  allTransactionsDescription:
    "Bütün kassa hesabları üzrə mədaxil, məxaric, xərc, transfer və ləğv hərəkətləri.",
  title: "Kassa",
  description:
    "Kassa hesablarını idarə edin. Əsas əməliyyatlar: Mədaxil, Məxaric, Xərc və Transfer.",
  reportsTitle: "Kassa hesabatları",
  reportsDescription:
    "Dövr üzrə cəmlər və hesab çıxarışı. Transfer gəlir/xərcə daxil edilmir; ləğv hərəkətləri dövriyyəni şişirtmir.",
  statementTitle: "Hesab çıxarışı",
  periodSummaryTitle: "Dövr cəmi",
  openingBalance: "Açılış qalığı",
  closingBalance: "Bağlanış qalığı",
  currentBalanceLabel: "Cari qalıq",
  signedEffect: "Təsir",
  runningBalance: "Axın qalığı",
  cashInTotal: "Mədaxil cəmi",
  cashOutTotal: "Məxaric cəmi",
  expenseTotal: "Xərc cəmi",
  transferTotal: "Transfer həcmi",
  partnerCashInTotal: "Tərəfdaş mədaxili",
  partnerCashOutTotal: "Tərəfdaş məxarici",
  dateRange: "Tarix aralığı",
  dateFrom: "Başlanğıc tarixi",
  dateTo: "Bitmə tarixi",
  cancelledCount: "Ləğv sayı",
  reversalCount: "Ləğv hərəkəti sayı",
  negativeAccountCount: "Mənfi qalıqlı hesab",
  expensesByCategory: "Kateqoriya üzrə xərclər",
  selectAccountForStatement: "Çıxarış üçün hesab seçin",
  selectAccountPlaceholder: "Kassa hesabı seçin",
  loadStatementHint: "Hesab seçildikdən sonra çıxarış yüklənir.",
  emptyStatement: "Bu dövr üçün əməliyyat yoxdur.",
  totalCompanyCash: "Şirkətin ümumi kassa qalığı",
  activeAccounts: "Aktiv hesab sayı",
  activeAccountSuffix: "aktiv hesab",
  companyCashHint: "Aktiv kassa hesablarının cari cəmi",
  accountsSectionTitle: "Kassa hesabları",
  accountsSectionDescription:
    "Qalıqları izləyin, gündəlik hərəkətləri yoxlayın və hesab üzrə əməliyyat başladın.",
  accountCountSuffix: "hesab",
  accountDetails: "Tarixçə və detallar",
  todayCashIn: "Bu günün mədaxili",
  todayCashOut: "Bu günün məxarici",
  todayExpenses: "Bu günün xərcləri",
  todaySummary: "Bu gün üzrə hərəkət",
  todayCashInShort: "Mədaxil",
  todayCashOutShort: "Məxaric",
  todayExpensesShort: "Xərc",
  recentActivity: "Son əməliyyatlar",
  primaryActions: "Əsas əməliyyatlar",
  requiredField: "Mütləq sahə",
  optionalField: "İstəyə bağlı",
  modalDescriptions: {
    accountCreate: "Yeni kassa hesabının əsas məlumatlarını daxil edin.",
    accountEdit: "Hesabın adını və əlavə qeydini yeniləyin.",
    cashIn: "Tərəfdaşdan qəbul edilən vəsaiti kassa hesabına qeyd edin.",
    cashOut: "Tərəfdaşa ödənilən vəsaiti kassa hesabından qeyd edin.",
    expense: "Biznes xərcini seçilmiş kassa hesabından qeyd edin.",
    transfer: "Vəsaiti iki kassa hesabı arasında köçürün.",
    categoryCreate: "Xərcləri qruplaşdırmaq üçün yeni kateqoriya yaradın.",
    categoryEdit: "Xərc kateqoriyasının adını yeniləyin.",
  },
  actionHints: {
    cashIn: "Tərəfdaşdan qəbul et",
    cashOut: "Tərəfdaşa ödə",
    expense: "Biznes xərcini qeyd et",
    transfer: "Hesablar arasında köçür",
  },
  createAccount: "Yeni kassa hesabı",
  editAccount: "Kassa hesabını redaktə et",
  cashIn: "Mədaxil",
  cashOut: "Məxaric",
  expense: "Xərc",
  transfer: "Transfer",
  expenseCategories: "Xərc kateqoriyaları",
  expenseCategoriesDescription:
    "Xərc əməliyyatları üçün kateqoriyaları idarə edin.",
  createExpenseCategory: "Yeni xərc kateqoriyası",
  editExpenseCategory: "Redaktə et",
  deactivate: "Deaktiv et",

  reactivate: "Aktivləşdir",
  viewHistory: "Tarixçə",
  cancelTxn: "Ləğv et",
  backToList: "Hesablara qayıt",
  historyTitle: "Əməliyyat tarixçəsi",
  retry: "Yenidən cəhd et",
  close: "Bağla",
  save: "Yadda saxla",
  confirm: "Təsdiqlə",
  cancel: "Ləğv et",
  negativeBalance: "Mənfi qalıq",
  statuses: {
    active: "Aktiv",
    inactive: "Deaktiv",
    POSTED: "Tamamlanıb",
    CANCELLED: "Ləğv edilib",
  },
  directions: {
    IN: "Mədaxil",
    OUT: "Məxaric",
  },
  types: {
    OTHER_INCOME: "Digər mədaxil",
    OWNER_DEPOSIT: "Kassaya pul qoyulması",
    OWNER_WITHDRAWAL: "Kassadan pul götürülməsi",
    MANUAL_ADJUSTMENT: "Düzəliş",
    OPENING_BALANCE: "İlkin qalıq",
    REVERSAL: "Ləğv hərəkəti",
    CUSTOMER_RECEIPT: "Mədaxil",
    SUPPLIER_PAYMENT: "Məxaric",
    EXPENSE: "Xərc",
    TRANSFER_OUT: "Transfer (çıxış)",
    TRANSFER_IN: "Transfer (giriş)",
  },
  columns: {
    code: "Kod",
    name: "Ad",
    balance: "Cari qalıq",
    responsible: "Məsul şəxs",
    status: "Status",
    actions: "Əməliyyatlar",
    date: "Tarix",
    number: "Nömrə",
    type: "Növ",
    amount: "Məbləğ",
    cashIn: "Mədaxil",
    cashOut: "Məxaric",
    balanceAfter: "Sonrakı qalıq",
    notes: "Qeyd",
    partner: "Tərəfdaş",
    createdBy: "Qeyd edən",
  },
  filters: {
    search: "Axtarış",
    searchPlaceholder: "Ad və ya kod üzrə axtarın",
    status: "Status",
    all: "Hamısı",
    txnStatus: "Əməliyyat statusu",
    txnStatusAll: "Hamısı",
    account: "Kassa hesabı",
    type: "Əməliyyat növü",
    direction: "İstiqamət",
    dateRange: "Tarix aralığı",
    dateFrom: "Başlanğıc tarixi",
    dateTo: "Bitmə tarixi",
    transactionNumber: "Əməliyyat nömrəsi",
    transactionNumberPlaceholder: "Məsələn, CSH-0000012",
    apply: "Filtrləri tətbiq et",
    reset: "Təmizlə",
    incoming: "Mədaxil",
    outgoing: "Məxaric",
  },
  fields: {
    name: "Hesab adı",
    namePlaceholder: "Məsələn, Ofis kassası",
    codeHint: "Kod avtomatik yaradılır və dəyişdirilə bilməz",
    notes: "Qeyd",
    notesPlaceholder: "Əlavə qeyd daxil edin (istəyə bağlı)",
    openingBalance: "İlkin qalıq",
    openingBalancePlaceholder: "0.00",
    openingBalanceHint:
      "Daxil etsəniz, hesab yaradılanda ilkin qalıq əməliyyatı yazılacaq",
    openingBalanceEditHint:
      "Yalnız Super Admin dəyişə bilər. Dəyişiklik mövcud ilkin qalıq əməliyyatını ləğv edib yenisini yazır; digər əməliyyatlar toxunulmur",
    responsibleUser: "Məsul şəxs",
    responsibleUserPlaceholder: "Məsul şəxsi seçin",
    responsibleUserHint:
      "Hər istifadəçiyə yalnız bir kassa hesabı təyin edilə bilər",
    responsibleUserAdminHint: "Məsul şəxsi yalnız Super Admin dəyişə bilər",
    amount: "Məbləğ",
    amountPlaceholder: "0.00",
    transactionDate: "Əməliyyat tarixi",
    cashInType: "Mədaxil növü",
    cashOutType: "Məxaric növü",
    expenseCategory: "Xərc kateqoriyası",
    expenseCategoryPlaceholder: "Kateqoriya seçin",
    typePlaceholder: "Növ seçin",
    account: "Kassa hesabı",
    accountPlaceholder: "Hesab seçin",
    sourceAccount: "Mənbə hesab",
    sourceAccountPlaceholder: "Mənbə hesabı seçin",
    destinationAccount: "Təyinat hesabı",
    destinationAccountPlaceholder: "Təyinat hesabı seçin",
    partner: "Tərəfdaş",
    partnerPlaceholder: "Tərəfdaş seçin",
    sale: "Əlaqəli satış",
    salePlaceholder: "Bağlantı yoxdur",
    purchase: "Əlaqəli alış",
    purchasePlaceholder: "Bağlantı yoxdur",
    noRelatedDocument: "Bağlantı yoxdur",
    noConnection: "Bağlantı yoxdur",
    relatedDocumentHint:
      "İstəyə bağlıdır. Yalnız izləmə üçündür; borc qalığı yenidən dəyişmir.",
    invoiceLinkedToCash: "Faktura kassa əməliyyatına bağlıdır",
    invoiceNotLinkedToCash: "Kassa əməliyyatı bağlı deyil",
    negativeReason: "Mənfi qalıq səbəbi",
    negativeReasonPlaceholder: "Yetərsiz qalıq üçün əsaslandırma yazın",
    cancelReason: "Ləğv səbəbi",
    cancelReasonPlaceholder: "Ləğv səbəbini yazın",
    deactivationReason: "Deaktivasiya səbəbi",
    deactivationReasonPlaceholder: "Səbəbi yazın (istəyə bağlı)",
  },
  preview: {
    balanceBefore: "Əvvəlki qalıq",
    amount: "Məbləğ",
    balanceAfter: "Sonrakı qalıq",
    partnerDebtBefore: "Tərəfdaş borcu əvvəl",
    partnerDebtAfter: "Tərəfdaş borcu sonra",
    sourceBalanceBefore: "Mənbə qalıq əvvəl",
    sourceBalanceAfter: "Mənbə qalıq sonra",
    destinationBalanceBefore: "Təyinat qalıq əvvəl",
    destinationBalanceAfter: "Təyinat qalıq sonra",
    totalCompanyCashUnchanged: "Şirkətin ümumi kassası dəyişmir",
    negativeWarning:
      "Bu məxaric hesabı mənfi qalığa salacaq. Davam etmək üçün səbəb yazın.",
    transferNegativeWarning:
      "Bu transfer mənbə hesabı mənfi qalığa salacaq. Davam etmək üçün səbəb yazın.",
  },
  confirmations: {
    cashInTitle: "Mədaxili təsdiqləyin",
    cashOutTitle: "Məxarici təsdiqləyin",
    expenseTitle: "Xərci təsdiqləyin",
    transferTitle: "Transferi təsdiqləyin",
    cashIn: (amount: string, account: string) =>
      `${amount} məbləği «${account}» hesabına mədaxil ediləcək və tərəfdaş borcu azalacaq.`,
    cashOut: (amount: string, account: string) =>
      `${amount} məbləği «${account}» hesabından məxaric ediləcək və tərəfdaş borcu artacaq.`,
    expense: (amount: string, account: string, category: string) =>
      `${amount} məbləğində «${category}» xərci «${account}» hesabından çıxarılacaq.`,
    transfer: (amount: string, source: string, destination: string) =>
      `${amount} məbləği «${source}» hesabından «${destination}» hesabına köçürüləcək. Şirkətin ümumi kassası dəyişməyəcək.`,
    cashOutNegative: (amount: string, account: string) =>
      `${amount} məbləği «${account}» hesabından çıxarılacaq və qalıq mənfi olacaq. Davam edilsin?`,
    deactivateTitle: "Hesabı deaktiv et",
    deactivate:
      "Bu kassa hesabı deaktiv ediləcək. Yeni mədaxil/məxaric mümkün olmayacaq. Davam edilsin?",
    reactivateTitle: "Hesabı aktivləşdir",
    reactivate: "Bu kassa hesabı yenidən aktivləşdiriləcək. Davam edilsin?",
    cancelTxnTitle: "Əməliyyatı ləğv et",
    cancelTxn:
      "Bu əməliyyat ləğv ediləcək və əks hərəkət yaradılacaq. Orijinal sətir saxlanılır. Ləğv səbəbi mütləqdir.",
    cancelEffectsTitle: "Ləğv nəticələri",
    cancelEffectsCashIn: [
      "Kassa hesabı orijinal məbləğ qədər azalacaq.",
      "Tərəfdaş borcu orijinal məbləğ qədər artacaq.",
      "Əlaqəli satış bağlantısı tarixçədə qalır; aktiv ödəniş sayılmır.",
      "Hesab qalığı mənfi ola bilər — mədaxil ləğvi yetərsiz qalıq səbəbilə bloklanmır.",
    ],
    cancelCashInMayGoNegative:
      "Diqqət: ləğvdən sonra kassa qalığı mənfi ola bilər. Bu, mədaxil ləğvi üçün icazəlidir; ayrıca mənfi-qalıq icazəsi tələb olunmur.",
    cancelEffectsCashOut: [
      "Kassa hesabı orijinal məbləğ qədər artacaq.",
      "Tərəfdaş borcu orijinal məbləğ qədər azalacaq.",
      "Əlaqəli alış bağlantısı tarixçədə qalır; aktiv ödəniş sayılmır.",
    ],
    cancelEffectsExpense: [
      "Kassa hesabı orijinal məbləğ qədər artacaq.",
      "Tərəfdaş borcu dəyişmir.",
      "Xərc kateqoriyası tarixçədə saxlanılır.",
    ],
    cancelEffectsTransfer: [
      "Mənbə hesab orijinal məbləğ qədər artacaq.",
      "Təyinat hesab orijinal məbləğ qədər azalacaq.",
      "Şirkətin ümumi kassası dəyişmir (transferdən əvvəlki vəziyyətə qayıdır).",
    ],
    cancelEffectsGeneric: [
      "Kassa balansı əks istiqamətdə düzəldiləcək.",
      "Orijinal və əks hərəkət tarixçədə görünəcək.",
    ],
  },
  empty: "Kassa hesabı tapılmadı",
  emptyHint: "Yeni kassa hesabı yaradaraq başlayın",
  emptyTxns: "Əməliyyat yoxdur",
  workspaceLoadError: "Kassa hesablarının gündəlik icmalı yüklənmədi.",
  workspaceUnavailable: "Gündəlik icmal əlçatan deyil.",
  unknownTransactionType: "Digər əməliyyat",
  relatedDocumentLoadError: "Sənədlər yüklənmədi. Yenidən cəhd edin.",
  inactiveAccountHint:
    "Hesab deaktivdir. Mədaxil və məxaric üçün əvvəlcə aktivləşdirin.",
  success: {
    created: "Kassa hesabı yaradıldı",
    updated: "Kassa hesabı yeniləndi",
    deactivated: "Kassa hesabı deaktiv edildi",
    reactivated: "Kassa hesabı aktivləşdirildi",
    cashIn: "Mədaxil qeydə alındı",
    cashOut: "Məxaric qeydə alındı",
    expense: "Xərc qeydə alındı",
    transfer: "Transfer qeydə alındı",
    categoryCreated: "Xərc kateqoriyası yaradıldı",
    categoryUpdated: "Xərc kateqoriyası yeniləndi",
    categoryDeactivated: "Xərc kateqoriyası deaktiv edildi",
    categoryReactivated: "Xərc kateqoriyası aktivləşdirildi",
    cancelled: "Əməliyyat ləğv edildi",
  },
  validation: {
    responsibleUserRequired: "Məsul şəxs seçilməlidir",
    nameRequired: "Hesab adı mütləqdir",
    categoryRequired: "Xərc kateqoriyası seçilməlidir",
    amountRequired: "Məbləğ mütləqdir",
    amountPositive: "Məbləğ sıfırdan böyük olmalıdır",
    amountFormat: "Düzgün məbləğ daxil edin (ən çoxu 2 onluq)",
    typeRequired: "Növ seçilməlidir",
    dateRequired: "Tarix mütləqdir",
    accountRequired: "Kassa hesabı seçilməlidir",
    partnerRequired: "Tərəfdaş seçilməlidir",
    destinationAccountRequired: "Təyinat hesabı seçilməlidir",
    transferAccountsDifferent: "Mənbə və təyinat hesabları fərqli olmalıdır",
    reasonRequired: "Səbəb mütləqdir",
    notesRequired: "Təsvir mütləqdir",
  },
} as const;
