/**
 * Azerbaijani UI labels for Users administration (ADR-005 / ADR-039).
 */
export const USERS_LABELS = {
  nav: 'İstifadəçilər',
  title: 'İstifadəçilər',
  description:
    'Yalnız Super Admin istifadəçi yarada, şifrə təyin edə və aktiv/deaktiv edə bilər.',
  create: 'Yeni istifadəçi',
  edit: 'İstifadəçini redaktə et',
  empty: 'Heç bir istifadəçi tapılmadı.',
  deactivateConfirm: 'Bu istifadəçini deaktiv etmək istəyirsiniz?',
  activateConfirm: 'Bu istifadəçini yenidən aktiv etmək istəyirsiniz?',
  fullName: 'Ad Soyad',
  fullNamePlaceholder: 'Məsələn: Əli Məmmədov',
  username: 'İstifadəçi adı',
  usernamePlaceholder: 'Giriş üçün unikal ad',
  password: 'Şifrə',
  passwordPlaceholder: 'Ən azı 8 simvol',
  passwordOptionalHint: 'Boş saxlasanız şifrə dəyişməz',
  newPassword: 'Yeni şifrə',
  status: 'Status',
  active: 'Aktiv',
  inactive: 'Deaktiv',
  roleBadge: 'Super Admin',
  cannotDeactivateSuperAdmin: 'Super Admin deaktiv edilə bilməz.',
  search: 'Axtarış',
  searchPlaceholder: 'Ad və ya istifadəçi adı',
  actions: 'Əməliyyatlar',
  editAction: 'Redaktə et',
  deactivate: 'Deaktiv et',
  activate: 'Aktivləşdir',
  save: 'Yadda saxla',
  cancel: 'Ləğv et',
  confirm: 'Təsdiqlə',
  retry: 'Yenidən cəhd et',
  createSuccess: 'İstifadəçi yaradıldı.',
  updateSuccess: 'İstifadəçi yeniləndi.',
  deactivateSuccess: 'İstifadəçi deaktiv edildi.',
  activateSuccess: 'İstifadəçi aktivləşdirildi.',
} as const;
