import { formatMoney } from '../../../shared/money/format-money';
import type { PurchaseStatus } from '../api/purchases.api';

export const PURCHASE_LABELS = {
  nav: 'Alışlar',
  title: 'Alışlar',
  description: 'Məhsul alışlarını yaradın, təsdiqləyin və izləyin.',
  create: 'Yeni alış',
  edit: 'Alışı redaktə et',
  detail: 'Alış məlumatları',
  printTitle: 'Alış sənədi',
  statuses: {
    DRAFT: 'Qaralama',
    POSTED: 'Təsdiqlənib',
    CANCELLED: 'Ləğv edilib',
  } satisfies Record<PurchaseStatus, string>,
  columns: {
    documentNumber: 'Sənəd nömrəsi',
    businessDate: 'Əməliyyat tarixi',
    partner: 'Təchizatçı',
    status: 'Status',
    itemCount: 'Sətir sayı',
    subtotal: 'Ara cəm',
    discount: 'Endirim',
    total: 'Yekun məbləğ',
    createdBy: 'Yaradan',
    createdAt: 'Yaradılma vaxtı',
    actions: 'Əməliyyatlar',
  },
  filters: {
    documentNumber: 'Sənəd nömrəsi',
    documentNumberPlaceholder: 'Sənəd nömrəsini axtarın',
    partner: 'Təchizatçı',
    status: 'Status',
    dateRange: 'Əməliyyat tarixi',
    dateFrom: 'Başlanğıc tarixi',
    dateTo: 'Bitmə tarixi',
    product: 'Məhsul',
    minTotal: 'Minimum məbləğ',
    maxTotal: 'Maksimum məbləğ',
    all: 'Hamısı',
  },
  fields: {
    partner: 'Təchizatçı',
    partnerPlaceholder: 'Təchizatçı seçin',
    businessDate: 'Əməliyyat tarixi',
    notes: 'Qeyd',
    notesPlaceholder: 'Alış barədə qeyd daxil edin',
    supplierInvoiceNumber: 'Təchizatçı faktura nömrəsi',
    supplierInvoicePlaceholder: 'Faktura nömrəsini daxil edin',
    documentDiscount: 'Sənəd endirimi',
    product: 'Məhsul',
    productPlaceholder: 'Məhsul seçin',
    availableQuantity: 'Cari miqdar',
    quantity: 'Miqdar',
    unitPrice: 'Vahid qiyməti',
    lineDiscount: 'Sətir endirimi',
    lineTotal: 'Sətir yekunu',
    lineNotes: 'Sətir qeydi',
    lineNotesPlaceholder: 'Sətir barədə qeyd',
    items: 'Məhsul sətirləri',
    partnerDebt: 'Cari borc qalığı',
    itemCount: 'Sətir sayı',
    totalQuantity: 'Ümumi miqdar',
    projectedDebt: 'Təsdiqdən sonra borc',
  },
  actions: {
    view: 'Bax',
    edit: 'Redaktə et',
    post: 'Təsdiqlə',
    remove: 'Sil',
    cancel: 'Ləğv et',
    save: 'Yadda saxla',
    saveAndPost: 'Təsdiqlə',
    back: 'Geri',
    addLine: 'Sətir əlavə et',
    removeLine: 'Sətiri sil',
    retry: 'Yenidən cəhd et',
    confirm: 'Təsdiqlə',
    print: 'Çap et',
  },
  post: {
    title: 'Alışı təsdiqləyirsiniz?',
    text: 'Təsdiqdən sonra məhsul miqdarı artacaq, tərəfdaşın borc qalığı azalacaq, alış redaktə üçün bağlanacaq. «İndi ödə» seçildikdə ayrıca Məxaric kassa əməliyyatı yaradılır.',
    payNow: 'İndi ödə',
    payNowHint:
      'Yalnız «Təsdiqlə» zamanı ayrıca Məxaric kassa əməliyyatı yaradılır.',
    cashAccount: 'Kassa hesabı',
    cashAccountPlaceholder: 'Kassa hesabı seçin',
    paymentAmount: 'Ödəniş məbləği',
    paymentAmountPlaceholder: '0.00',
    paymentAmountHint:
      'Qismən və ya sənəd məbləğindən artıq ödənişə icazə verilir.',
    immediatePaymentRequired: 'Ödəniş üçün kassa hesabı və məbləğ mütləqdir.',
    previewTitle: 'Təsdiqdən sonra təxmini qalıqlar',
    partnerDebtBefore: 'Tərəfdaş borcu (əvvəl)',
    partnerDebtAfter: 'Tərəfdaş borcu (sonra)',
    cashBefore: 'Kassa qalığı (əvvəl)',
    cashAfter: 'Kassa qalığı (sonra)',
    success: 'Alış təsdiqləndi.',
  },
  cancel: {
    title: 'Alışı ləğv edirsiniz?',
    text: 'Bu tamamlanmış alışı ləğv etmək geri qaytarıla bilməz. Aşağıdakı təsirlər eyni vaxtda tətbiq olunacaq.',
    effectsTitle: 'Ləğv nəticələri',
    effects: [
      'Məhsul miqdarı orijinal qəbul qədər azalacaq (tarixçə saxlanılır).',
      'Tərəfdaş borcu orijinal alış məbləği qədər artacaq (borc hərəkəti saxlanılır).',
      'Kassa balansı bu ləğvdən dəyişmir — əlaqəli tamamlanmış məxarici əvvəlcə ayrıca ləğv edin.',
      'Sənəd «Ləğv edilib» statusunda qalır; yenidən təsdiq edilə bilməz.',
    ],
    insufficientQuantityHint:
      'Əgər məhsul sonradan satılıbsa və ya sərf olunubsa, ləğv bloklanacaq. Əvvəlcə həmin hərəkətləri həll edin.',
    reason: 'Ləğv səbəbi',
    reasonPlaceholder: 'Ləğv səbəbini daxil edin',
    reasonRequired: 'Ləğv səbəbi mütləqdir.',
    success: 'Alış ləğv edildi.',
  },
  remove: {
    title: 'Qaralama alış silinsin?',
    text: 'Bu əməliyyatı geri qaytarmaq mümkün deyil.',
    success: 'Qaralama alış silindi.',
  },
  messages: {
    empty: 'Alış tapılmadı.',
    loading: 'Məlumatlar yüklənir...',
    loadError: 'Alış məlumatlarını yükləmək mümkün olmadı.',
    printOpenError: 'Çap pəncərəsini açmaq mümkün olmadı.',
    createSuccess: 'Qaralama alış yaradıldı.',
    updateSuccess: 'Qaralama alış yeniləndi.',
    draftOnly: 'Yalnız qaralama alış redaktə edilə bilər.',
  },
  audit: {
    title: 'Audit məlumatları',
    createdBy: 'Yaradan',
    postedBy: 'Təsdiqləyən',
    cancelledBy: 'Ləğv edən',
    postedAt: 'Təsdiq vaxtı',
    cancelledAt: 'Ləğv vaxtı',
    cancelReason: 'Ləğv səbəbi',
  },
  history: {
    quantity: 'Miqdar tarixçəsi',
    debt: 'Borc hərəkətləri',
    cash: 'Əlaqəli kassa əməliyyatları',
    cashCancelledHint:
      'Ləğv edilmiş kassa əməliyyatları aktiv ödəniş sayılmır; tarixçə üçün saxlanılır.',
    change: 'Dəyişiklik',
    before: 'Əvvəl',
    after: 'Sonra',
    reason: 'Səbəb',
    date: 'Tarix',
    signedAmount: 'Məbləğ təsiri',
    transactionNumber: 'Əməliyyat №',
    cashAccount: 'Kassa hesabı',
    amount: 'Məbləğ',
  },
  formatMoney,
} as const;

export function purchaseStatusLabel(status: PurchaseStatus): string {
  return PURCHASE_LABELS.statuses[status];
}
