import { formatMoney } from '../../../shared/money/format-money';
import type { PurchaseStatus } from '../api/purchases.api';

export const PURCHASE_LABELS = {
  nav: 'Alışlar',
  title: 'Alışlar',
  description: 'Məhsul alışlarını yaradın, təsdiqləyin və izləyin.',
  create: 'Yeni alış',
  edit: 'Alışı redaktə et',
  detail: 'Alış məlumatları',
  statuses: {
    DRAFT: 'Qaralama',
    POSTED: 'Təsdiqlənib',
    CANCELLED: 'Ləğv edilib',
  } satisfies Record<PurchaseStatus, string>,
  columns: {
    documentNumber: 'Sənəd nömrəsi',
    businessDate: 'Əməliyyat tarixi',
    partner: 'Təchizatçı',
    status: 'Status',
    itemCount: 'Sətir sayı',
    subtotal: 'Ara cəm',
    discount: 'Endirim',
    total: 'Yekun məbləğ',
    createdBy: 'Yaradan',
    createdAt: 'Yaradılma vaxtı',
    actions: 'Əməliyyatlar',
  },
  filters: {
    documentNumber: 'Sənəd nömrəsi',
    documentNumberPlaceholder: 'Sənəd nömrəsini axtarın',
    partner: 'Təchizatçı',
    status: 'Status',
    dateRange: 'Əməliyyat tarixi',
    product: 'Məhsul',
    minTotal: 'Minimum məbləğ',
    maxTotal: 'Maksimum məbləğ',
    all: 'Hamısı',
  },
  fields: {
    partner: 'Təchizatçı',
    partnerPlaceholder: 'Təchizatçı seçin',
    businessDate: 'Əməliyyat tarixi',
    notes: 'Qeyd',
    notesPlaceholder: 'Alış barədə qeyd daxil edin',
    supplierInvoiceNumber: 'Təchizatçı faktura nömrəsi',
    supplierInvoicePlaceholder: 'Faktura nömrəsini daxil edin',
    documentDiscount: 'Sənəd endirimi',
    product: 'Məhsul',
    productPlaceholder: 'Məhsul seçin',
    quantity: 'Miqdar',
    unitPrice: 'Vahid qiyməti',
    lineDiscount: 'Sətir endirimi',
    lineTotal: 'Sətir yekunu',
    lineNotes: 'Sətir qeydi',
    lineNotesPlaceholder: 'Sətir barədə qeyd',
    items: 'Məhsul sətirləri',
  },
  actions: {
    view: 'Bax',
    edit: 'Redaktə et',
    post: 'Təsdiqlə',
    remove: 'Sil',
    cancel: 'Ləğv et',
    save: 'Yadda saxla',
    saveAndPost: 'Yadda saxla və təsdiqlə',
    back: 'Geri',
    addLine: 'Sətir əlavə et',
    removeLine: 'Sətiri sil',
    retry: 'Yenidən cəhd et',
    confirm: 'Təsdiqlə',
  },
  post: {
    title: 'Alışı təsdiqləyirsiniz?',
    text: 'Təsdiqdən sonra məhsul miqdarı artacaq, tərəfdaşın borc qalığı azalacaq, alış redaktə üçün bağlanacaq və pul qalığı dəyişməyəcək.',
    success: 'Alış təsdiqləndi.',
  },
  cancel: {
    title: 'Alışı ləğv edirsiniz?',
    text: 'Ləğv etmə məhsul miqdarı və tərəfdaş borcu təsirlərini geri qaytaracaq. Pul qalığı dəyişməyəcək.',
    reason: 'Ləğv səbəbi',
    reasonPlaceholder: 'Ləğv səbəbini daxil edin',
    reasonRequired: 'Ləğv səbəbi mütləqdir.',
    success: 'Alış ləğv edildi.',
  },
  remove: {
    title: 'Qaralama alış silinsin?',
    text: 'Bu əməliyyatı geri qaytarmaq mümkün deyil.',
    success: 'Qaralama alış silindi.',
  },
  messages: {
    empty: 'Alış tapılmadı.',
    loading: 'Məlumatlar yüklənir...',
    loadError: 'Alış məlumatlarını yükləmək mümkün olmadı.',
    createSuccess: 'Qaralama alış yaradıldı.',
    updateSuccess: 'Qaralama alış yeniləndi.',
    draftOnly: 'Yalnız qaralama alış redaktə edilə bilər.',
  },
  audit: {
    title: 'Audit məlumatları',
    createdBy: 'Yaradan',
    postedBy: 'Təsdiqləyən',
    cancelledBy: 'Ləğv edən',
    postedAt: 'Təsdiq vaxtı',
    cancelledAt: 'Ləğv vaxtı',
    cancelReason: 'Ləğv səbəbi',
  },
  history: {
    quantity: 'Miqdar tarixçəsi',
    debt: 'Borc hərəkətləri',
    change: 'Dəyişiklik',
    before: 'Əvvəl',
    after: 'Sonra',
    reason: 'Səbəb',
    date: 'Tarix',
    signedAmount: 'Məbləğ təsiri',
  },
  formatMoney,
} as const;

export function purchaseStatusLabel(status: PurchaseStatus): string {
  return PURCHASE_LABELS.statuses[status];
}
