export const AUTH_LABELS = {
  loginTitle: 'Daxil ol',
  loginDescription: 'İstifadəçi adı və şifrə ilə sistemə daxil olun.',
  username: 'İstifadəçi adı',
  usernamePlaceholder: 'İstifadəçi adınızı daxil edin',
  password: 'Şifrə',
  passwordPlaceholder: 'Şifrənizi daxil edin',
  submit: 'Daxil ol',
  logout: 'Çıxış',
  invalidCredentials: 'İstifadəçi adı və ya şifrə yanlışdır.',
  sessionExpired: 'Sessiya bitib. Yenidən daxil olun.',
  accountNav: 'Hesab',
  accountTitle: 'Hesab ayarları',
  accountDescription: 'Profil məlumatlarınıza baxın və şifrənizi dəyişin.',
  changePasswordTitle: 'Şifrəni dəyiş',
  currentPassword: 'Cari şifrə',
  currentPasswordPlaceholder: 'Hazırkı şifrənizi daxil edin',
  newPassword: 'Yeni şifrə',
  newPasswordPlaceholder: 'Ən azı 8 simvol',
  newPasswordConfirmation: 'Yeni şifrənin təkrarı',
  newPasswordConfirmationPlaceholder: 'Yeni şifrəni təkrar daxil edin',
  changePasswordSubmit: 'Şifrəni yenilə',
  changePasswordSuccess:
    'Şifrə dəyişdirildi. Təhlükəsizlik üçün yenidən daxil olun.',
  wrongCurrentPassword: 'Cari şifrə yanlışdır.',
  passwordMismatch: 'Yeni şifrə və təkrarı eyni olmalıdır.',
  passwordTooShort: 'Şifrə ən azı 8 simvol olmalıdır.',
  passwordUnchanged: 'Yeni şifrə cari şifrədən fərqli olmalıdır.',
  pushTitle: 'Bildirişlər',
  pushDescription:
    'Biznes əməliyyatları haqqında qısa sistem bildirişləri alın. İcazə yalnız sizin klikinizdən sonra soruşulur.',
  pushEnable: 'Bildirişləri aktiv et',
  pushDisable: 'Bildirişləri söndür',
  pushEnableSuccess: 'Bildirişlər aktivləşdirildi.',
  pushDisableSuccess: 'Bildirişlər söndürüldü.',
  pushLoading: 'Bildiriş statusu yoxlanılır…',
  pushUnsupported:
    'Bu brauzer Web Push bildirişlərini dəstəkləmir.',
  pushDenied:
    'Bildiriş icazəsi rədd edilib. Brauzer və ya sistem ayarlarından əl ilə aktivləşdirin.',
  pushSubscribed: 'Bu cihazda bildirişlər aktivdir.',
  pushServerDisabled:
    'Bildiriş xidməti hazırda serverdə konfiqurasiya olunmayıb.',
  pushIosHomescreenTitle: 'iOS üçün Əsas ekrana əlavə edin',
  pushIosHomescreenDescription:
    'iPhone/iPad-də Web Push yalnız Əsas ekrana əlavə edilmiş TOPTANFLOW tətbiqindən işləyir. Safari Paylaş → Əsas ekrana əlavə et, sonra tətbiqi açın və bildirişləri aktiv edin.',
} as const;
