/** Approved owner labels for US-038 reference-data screens (2026-07-29). */
export const MASTER_DATA_LABELS = {
  currencies: {
    nav: 'Valyutalar',
    title: 'Valyutalar',
    create: 'Yeni valyuta',
    edit: 'Valyutanı redaktə et',
    empty: 'Heç bir valyuta tapılmadı.',
    deactivateConfirm: 'Bu valyutanı deaktiv etmək istəyirsiniz?',
  },
  units: {
    nav: 'Ölçü vahidləri',
    title: 'Ölçü vahidləri',
    create: 'Yeni ölçü vahidi',
    edit: 'Ölçü vahidini redaktə et',
    empty: 'Heç bir ölçü vahidi tapılmadı.',
    deactivateConfirm: 'Bu ölçü vahidini deaktiv etmək istəyirsiniz?',
  },
  common: {
    code: 'Kod',
    name: 'Ad',
    symbol: 'Simvol',
    status: 'Status',
    active: 'Aktiv',
    inactive: 'Deaktiv',
    search: 'Axtarış',
    filterStatus: 'Status filtri',
    all: 'Hamısı',
    actions: 'Əməliyyatlar',
    edit: 'Redaktə et',
    deactivate: 'Deaktiv et',
    save: 'Yadda saxla',
    cancel: 'Ləğv et',
    createSuccess: 'Qeyd yaradıldı.',
    updateSuccess: 'Qeyd yeniləndi.',
    deactivateSuccess: 'Qeyd deaktiv edildi.',
    loading: 'Yüklənir…',
    loadError: 'Məlumatlar yüklənmədi.',
    retry: 'Yenidən cəhd et',
    fractional: 'Fraksiyalı miqdar icazəsi',
    yes: 'Bəli',
    no: 'Xeyr',
    confirm: 'Təsdiq et',
  },
} as const;
