/**
 * Owner guidance (2026-07-29): agents may choose clear Azerbaijani UI labels
 * for known delivered enums without stopping the task for confirmation.
 */
export const MASTER_DATA_LABELS = {
  currencies: {
    nav: 'Valyutalar',
    title: 'Valyutalar',
    description: 'Sistemdə istifadə olunan valyuta istinadları.',
    create: 'Yeni valyuta',
    edit: 'Valyutanı redaktə et',
    empty: 'Heç bir valyuta tapılmadı.',
    deactivateConfirm: 'Bu valyutanı deaktiv etmək istəyirsiniz?',
    activateConfirm: 'Bu valyutanı yenidən aktiv etmək istəyirsiniz?',
  },
  units: {
    nav: 'Ölçü vahidləri',
    title: 'Ölçü vahidləri',
    description: 'Miqdar ölçüsü üçün vahid istinadları.',
    create: 'Yeni ölçü vahidi',
    edit: 'Ölçü vahidini redaktə et',
    empty: 'Heç bir ölçü vahidi tapılmadı.',
    deactivateConfirm: 'Bu ölçü vahidini deaktiv etmək istəyirsiniz?',
    activateConfirm: 'Bu ölçü vahidini yenidən aktiv etmək istəyirsiniz?',
  },
  categories: {
    nav: 'Kateqoriyalar',
    title: 'Məhsul kateqoriyaları',
    description: 'Məhsullar üçün düz (ixtiyari) kateqoriya siyahısı.',
    create: 'Yeni kateqoriya',
    edit: 'Kateqoriyanı redaktə et',
    empty: 'Heç bir kateqoriya tapılmadı.',
    deactivateConfirm: 'Bu kateqoriyanı deaktiv etmək istəyirsiniz?',
    activateConfirm: 'Bu kateqoriyanı yenidən aktiv etmək istəyirsiniz?',
    namePlaceholder: 'Məsələn: Tekstil',
  },
  products: {
    nav: 'Məhsullar',
    title: 'Məhsullar',
    description: 'Məhsul kataloqu, tip, kateqoriya və qiymət məlumatları.',
    create: 'Yeni məhsul',
    edit: 'Məhsulu redaktə et',
    empty: 'Heç bir məhsul tapılmadı.',
    deactivateConfirm: 'Bu məhsulu deaktiv etmək istəyirsiniz?',
    activateConfirm: 'Bu məhsulu yenidən aktiv etmək istəyirsiniz?',
    type: 'Tip',
    typePlaceholder: 'Tip seçin',
    category: 'Kateqoriya',
    categoryPlaceholder: 'Kateqoriya seçin',
    filterCategory: 'Kateqoriya',
    unit: 'Ölçü vahidi',
    unitPlaceholder: 'Ölçü vahidi seçin',
    standardSalePrice: 'Standart satış qiyməti',
    latestPurchasePrice: 'Son alış qiyməti',
    criticalStockThreshold: 'Kritik stok həddi',
    decimalPlaceholder: '0.0000',
    filterType: 'Tip',
    codeReadonlyHint: 'Kod sistem tərəfindən yaradılır və dəyişdirilə bilməz.',
    types: {
      FINISHED_GOOD: 'Hazır məhsul',
      RAW_MATERIAL: 'Xammal',
      MIXED_USE: 'Qarışıq təyinatlı',
    },
  },
  partners: {
    nav: 'Biznes tərəfdaşları',
    title: 'Biznes tərəfdaşları',
    description: 'Müştəri və təchizatçı qeydləri.',
    create: 'Yeni tərəfdaş',
    edit: 'Tərəfdaşı redaktə et',
    empty: 'Heç bir tərəfdaş tapılmadı.',
    deactivateConfirm: 'Bu tərəfdaşı deaktiv etmək istəyirsiniz?',
    activateConfirm: 'Bu tərəfdaşı yenidən aktiv etmək istəyirsiniz?',
    role: 'Rol',
    customer: 'Müştəri',
    supplier: 'Təchizatçı',
    bothRoles: 'Hər ikisi',
    filterRole: 'Rol',
    defaultCurrency: 'Defolt valyuta',
    defaultCurrencyPlaceholder: 'Valyuta seçin',
    phone: 'Telefon',
    phonePlaceholder: 'Məsələn: +994501234567',
    email: 'E-poçt',
    emailPlaceholder: 'meselen@ornek.az',
    taxNumber: 'Vergi nömrəsi',
    taxNumberPlaceholder: 'Vergi nömrəsini daxil edin',
    address: 'Ünvan',
    addressPlaceholder: 'Ünvanı daxil edin',
    notes: 'Qeydlər',
    notesPlaceholder: 'Əlavə qeydlər (ixtiyari)',
    codeReadonlyHint: 'Kod sistem tərəfindən yaradılır və dəyişdirilə bilməz.',
    duplicateTitle: 'Oxşar tərəfdaşlar tapıldı',
    duplicateIntro:
      'Eyni ad, telefon və ya vergi nömrəsinə oxşayan mövcud qeydlər var. Davam etmək üçün açıq şəkildə təsdiqləyin.',
    duplicateAcknowledge: 'Buna baxmayaraq yadda saxla',
    matchedFields: 'Uyğun sahələr',
    matched: {
      name: 'Ad',
      phone: 'Telefon',
      taxNumber: 'Vergi nömrəsi',
    },
  },
  warehouses: {
    nav: 'Anbarlar',
    title: 'Anbarlar',
    description: 'Anbar istinad məlumatları və növ təyinatı.',
    create: 'Yeni anbar',
    edit: 'Anbarı redaktə et',
    empty: 'Heç bir anbar tapılmadı.',
    deactivateConfirm: 'Bu anbarı deaktiv etmək istəyirsiniz?',
    activateConfirm: 'Bu anbarı yenidən aktiv etmək istəyirsiniz?',
    kind: 'Növ',
    kindPlaceholder: 'Növ seçin',
    filterKind: 'Növ',
    codeReadonlyHint: 'Kod sistem tərəfindən yaradılır və dəyişdirilə bilməz.',
    kinds: {
      GENERAL: 'Ümumi',
      DAMAGED: 'Zədələnmiş',
    },
  },
  common: {
    code: 'Kod',
    name: 'Ad',
    namePlaceholder: 'Adı daxil edin',
    symbol: 'Simvol',
    status: 'Status',
    active: 'Aktiv',
    inactive: 'Deaktiv',
    search: 'Axtarış',
    searchPlaceholder: 'Kod və ya ada görə axtarın',
    filterStatus: 'Status',
    all: 'Hamısı',
    actions: 'Əməliyyatlar',
    edit: 'Redaktə et',
    deactivate: 'Deaktiv et',
    activate: 'Aktiv et',
    save: 'Yadda saxla',
    cancel: 'Ləğv et',
    createSuccess: 'Qeyd yaradıldı.',
    updateSuccess: 'Qeyd yeniləndi.',
    deactivateSuccess: 'Qeyd deaktiv edildi.',
    activateSuccess: 'Qeyd aktiv edildi.',
    loading: 'Yüklənir…',
    loadError: 'Məlumatlar yüklənmədi.',
    retry: 'Yenidən cəhd et',
    fractional: 'Fraksiyalı miqdar icazəsi',
    yes: 'Bəli',
    no: 'Xeyr',
    confirm: 'Təsdiq et',
  },
} as const;

export type ProductTypeLabelKey =
  keyof typeof MASTER_DATA_LABELS.products.types;

export function productTypeLabel(type: ProductTypeLabelKey): string {
  return MASTER_DATA_LABELS.products.types[type];
}

export type WarehouseKindLabelKey =
  keyof typeof MASTER_DATA_LABELS.warehouses.kinds;

export function warehouseKindLabel(kind: WarehouseKindLabelKey): string {
  return MASTER_DATA_LABELS.warehouses.kinds[kind];
}
