// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
    // Infrastructure-only, intentional no-op seed (apps/api/prisma/seed.ts);
    // see docs/technical/database-development.md. Runs after `prisma migrate
    // dev` / `prisma migrate reset`, and via `prisma db seed` directly.
    seed: 'ts-node prisma/seed.ts',
  },
  datasource: {
    url: process.env['DATABASE_URL'],
  },
});
